name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]          # لو الفرع اسمه master غيّره هنا
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# يمنع تعارض تشغيلات متعددة
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # تهيئة GitHub Pages
      - name: Prepare static output
  run: |
    set -e
    mkdir -p dist
    cp -f index.html dist/ || true
    cp -f styles.css dist/ || true
    if [ -d images ]; then cp -r images dist/images; fi
    if [ -d downloads ]; then cp -r downloads dist/downloads; fi
    # ملفات السيو:
    if [ -f robots.txt ]; then cp robots.txt dist/; fi
    if [ -f sitemap.xml ]; then cp sitemap.xml dist/; fi
    if [ -f 404.html ]; then cp 404.html dist/; fi
    touch dist/.nojekyll


      # رفع ملفات الموقع كـ Artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          timeout: 1800000          # 30 دقيقة
          error_count: 30
          reporting_interval: 10000
